name: Deploy Nextjs to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/web_deploy.yml'
      - 'apps/web/**'
      - 'packages/styles/**'
      - 'packages/ui/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Build @giffy/styles
        working-directory: ./packages/styles
        run: yarn build

      - name: Compile @giffy/styles
        working-directory: ./packages/styles
        run: yarn start

      - name: Build @giffy/ui
        working-directory: ./packages/ui
        run: yarn build

      - name: Build Storybook
        working-directory: ./packages/ui
        run: yarn build-storybook-nextjs

      - name: Build @giffy/web
        working-directory: ./apps/web
        run: yarn gh-build
        env:
          NEXT_PUBLIC_FORM_URL: ${{ secrets.NEXT_PUBLIC_FORM_URL }}
          NEXT_PUBLIC_GIFFY_STUDIO_PAYMENT_LINK: ${{ secrets.NEXT_PUBLIC_GIFFY_STUDIO_PAYMENT_LINK }}
          NEXT_PUBLIC_GIFFY_BUSINESS_PAYMENT_LINK: ${{ secrets.NEXT_PUBLIC_GIFFY_BUSINESS_PAYMENT_LINK }}

      - name: Export static files
        working-directory: ./apps/web
        run: yarn export
        env:
          NEXT_PUBLIC_FORM_URL: ${{ secrets.NEXT_PUBLIC_FORM_URL }}
          NEXT_PUBLIC_GIFFY_STUDIO_PAYMENT_LINK: ${{ secrets.NEXT_PUBLIC_GIFFY_STUDIO_PAYMENT_LINK }}
          NEXT_PUBLIC_GIFFY_BUSINESS_PAYMENT_LINK: ${{ secrets.NEXT_PUBLIC_GIFFY_BUSINESS_PAYMENT_LINK }}

      - name: Add .nojekyll file
        working-directory: ./apps/web
        run: touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./apps/web/out
